#!/usr/bin/env python

import sys
import os
# Set sys.path for git-fat import
test_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.normpath(os.path.join(test_dir, '../git_fat')))

from git_fat import main

if __name__ == '__main__':
    main()
